[build]
  command = "npm run build"
  publish = "dist"

# Ensure SPA routing works by redirecting all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add CSP headers to allow hCaptcha
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.hcaptcha.com; frame-src 'self' https://*.hcaptcha.com; style-src 'self' 'unsafe-inline' https://*.hcaptcha.com; connect-src 'self' https://*.hcaptcha.com; img-src 'self' data: https://*.hcaptcha.com; font-src 'self' data:;"

# Optional: local Netlify Dev settings for Vite
[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080
  framework = "vite"