# netlify.toml — Vite React SPA: dev proxy, SPA fallback, headers, env

redirectsOrigin = "config"
plugins = []

########################################
# Local development (netlify dev)
########################################
[dev]
# Jalankan Vite dev (bukan preview)
command = "npm run dev"
# Port yang dipakai Netlify Dev (bebas)
port = 8888
# Port internal Vite dev server (default 5173)
targetPort = 5173
# framework bisa dihapus; Netlify auto-detect

########################################
# Build & publish
########################################
[build]
command = "npm run build"
publish = "dist"
publishOrigin = "config"
commandOrigin = "config"

# Env yang akan tersedia di bundle (awalan VITE_)
[build.environment]
  VITE_NETLIFY_CONTEXT = "${CONTEXT}" # "production" | "deploy-preview" | "branch-deploy"

  # ---- (PILIH SATU) ----
  # Opsi A: disable secret scan (paling simpel)
  SECRETS_SCAN_ENABLED = "false"

  # Opsi B (alternatif): biarkan scan aktif tapi whitelist VITE_* keys publik
  # SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_HCAPTCHA_SITE_KEY,VITE_HCAPTCHA_ENABLED,VITE_APP_NAME,VITE_APP_VERSION,VITE_DEV_HOSTS,VITE_FORCE_LOGS"
  # SECRETS_SCAN_OMIT_PATHS = "dist/**"
  # NODE_VERSION = "18"

########################################
# Headers
########################################

# Cache panjang utk asset hashed
[[headers]]
for = "/assets/*.js"
  [headers.values]
  Content-Type = "application/javascript"
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*.css"
  [headers.values]
  Content-Type = "text/css"
  Cache-Control = "public, max-age=31536000, immutable"

# HTML revalidate (biar fetch terbaru tiap reload)
[[headers]]
for = "/"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

# File lain (opsional)
[[headers]]
for = "/*.svg"
  [headers.values]
  Content-Type = "image/svg+xml"

[[headers]]
for = "/*.json"
  [headers.values]
  Content-Type = "application/json"

# 🔐 Content Security Policy
# Mengizinkan:
# - hCaptcha
# - Supabase Realtime (https & wss)
# - Inline style (diperlukan utk beberapa UI lib)
[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-inline' https://js.hcaptcha.com;
    style-src  'self' 'unsafe-inline';
    img-src    'self' data: https://*.hcaptcha.com;
    font-src   'self' data:;
    connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.hcaptcha.com;
    frame-src  https://*.hcaptcha.com;
    base-uri   'self';
    form-action 'self';
  """
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"

########################################
# SPA fallback
########################################
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
