// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Get environment variables (trim biar aman)
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || "").trim();
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY || "").trim();

// Debug log hanya di DEV
if (import.meta.env.DEV) {
  console.log("🔥 Supabase Client Debug:", {
    VITE_SUPABASE_URL: SUPABASE_URL ? "PRESENT" : "MISSING",
    VITE_SUPABASE_ANON_KEY: SUPABASE_PUBLISHABLE_KEY ? "PRESENT" : "MISSING",
    mode: import.meta.env.MODE,
  });
}

// Validate required environment variables
if (!SUPABASE_URL) {
  console.error("🔥 CRITICAL: SUPABASE_URL is missing or empty", {
    url: SUPABASE_URL,
    env: import.meta.env,
  });
  throw new Error(
    "Missing VITE_SUPABASE_URL environment variable. Set it in .env or Netlify dashboard."
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error("🔥 CRITICAL: SUPABASE_PUBLISHABLE_KEY is missing or empty", {
    key: SUPABASE_PUBLISHABLE_KEY,
    env: import.meta.env,
  });
  throw new Error(
    "Missing VITE_SUPABASE_ANON_KEY environment variable. Set it in .env or Netlify dashboard."
  );
}

// Export client
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);

// Optional: expose in dev for easier debugging
if (import.meta.env.DEV) {
  (window as any).supabase = supabase;
}
