// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kewhzkfvswbimmwtpymw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtld2h6a2Z2c3diaW1td3RweW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzI4MTcsImV4cCI6MjA2NjQwODgxN30.Pz3Q7ll6qHKUFkSJTvaa0Aqgk0Jh_T6G_qFTaEDn33w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);