name: Deploy Supabase Edge Functions

on:
  push:
    branches: [ dev3 ]
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:
    inputs:
      project_ref:
        description: 'Supabase project ref (overrides default)'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          set -e
          PROJECT_REF="${{ github.event.inputs.project_ref }}"
          if [ -z "$PROJECT_REF" ]; then PROJECT_REF="kewhzkfvswbimmwtpymw"; fi
          echo "Deploying to project: $PROJECT_REF"
          supabase functions deploy scalev-webhook --project-ref "$PROJECT_REF"

      - name: Verify endpoint (preflight + POST) - dev and prod origins
        run: |
          set -e
          PROJECT_REF="${{ github.event.inputs.project_ref }}"
          if [ -z "$PROJECT_REF" ]; then PROJECT_REF="kewhzkfvswbimmwtpymw"; fi

          DEV_URL="${{ vars.NETLIFY_DEV_URL }}"
          if [ -z "$DEV_URL" ]; then DEV_URL="https://dev3--gleaming-peony-f4a091.netlify.app"; fi
          PROD_URL="https://kalkulator.monifine.my.id"

          FN_BASE="https://$PROJECT_REF.functions.supabase.co"
          FN_ENDPOINT="$FN_BASE/scalev-webhook"

          echo "Testing preflight (DEV origin): $DEV_URL"
          curl -s -f -X OPTIONS "$FN_ENDPOINT" \
            -H "Origin: $DEV_URL" \
            -H "Access-Control-Request-Method: POST" >/dev/null

          echo "Testing preflight (PROD origin): $PROD_URL"
          curl -s -f -X OPTIONS "$FN_ENDPOINT" \
            -H "Origin: $PROD_URL" \
            -H "Access-Control-Request-Method: POST" >/dev/null

          echo "Testing POST (DEV origin)"
          curl -s -f -X POST "$FN_ENDPOINT" \
            -H "Origin: $DEV_URL" \
            -H "Content-Type: application/json" \
            -d '{"data":{"order_id":"CI-TEST-DEV","payment_status":"unpaid","email":"ci@example.com"}}' >/dev/null

          echo "Testing POST (PROD origin)"
          curl -s -f -X POST "$FN_ENDPOINT" \
            -H "Origin: $PROD_URL" \
            -H "Content-Type: application/json" \
            -d '{"data":{"order_id":"CI-TEST-PROD","payment_status":"unpaid","email":"ci@example.com"}}' >/dev/null

          echo "All endpoint checks passed."
